# SEO Values
title: "BASU"
tagline:
description: Welcome to my bio.
url: https://github.com/surattinon

# Google Analytics ID
# google_analytics:

# GitHub Values
github:
  owner_name: surattinon
  owner_url: https://github.com/surattinon
  repository_url: https://github.com/surattinon

show_downloads: false
show_header: false
remote_theme: "dracula/gh-pages"

sass:
  style: compressed

plugins:
  - jekyll-seo-tag
