# SEO Values
title: "BASU"
tagline:
description: Welcome to my github page.
url: https://github.com/surattinon

# Google Analytics ID
# google_analytics:

# GitHub Values
github:
  owner_name: Dracula
  owner_url: https://github.com/dracula
  repository_url: https://github.com/dracula/gh-pages

show_downloads: false
show_header: false
remote_theme: "dracula/gh-pages"

sass:
  style: compressed

plugins:
  - jekyll-seo-tag
